### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit__moveit_roscpp_initializer)

### ISSUE THREAD

**Issue by Alan963852741** [Shaluols/ur5e_dmp#1]
Hello
I got some bugs when I run " python dmp_ur5e_test.py "

Could you tell me how to solve it?

Thanks!

```
r3@r3-C246-WU4:~/code_FromGitHub/ur5e_dmp$ python dmp_ur5e_test.py 
Traceback (most recent call last):
  File "dmp_ur5e_test.py", line 6, in <module>
    import rospy, moveit_commander, moveit_msgs
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/moveit_commander/__init__.py", line 2, in <module>
    from .roscpp_initializer import *
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/moveit_commander/roscpp_initializer.py", line 35, in <module>
    from moveit_ros_planning_interface import _moveit_roscpp_initializer
ImportError: dynamic module does not define module export function (PyInit__moveit_roscpp_initializer)
```

**Comment by Shaluols** [comment]
Hi,

I did not experience this problem before, I think it is related to the installation and dependencies of Moveit, please check if your Moveit successfully installed.
